#---
# .zshrc file to load user specific settings
#

export PATH="/opt/homebrew/bin:$HOME/.macdots/scripts:$PATH"
export EDITOR="vim -u ~/.dev/.macdots/vim/vimrc"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

# Needed for pyenv to find different version of python
eval "$(pyenv init -)"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"


PROMPT="%F{158}DevNetKid%f %F{cyan}%~:%f >> "

# Basic terminal commands
alias ll='ls -alF --color'
alias grep='ggrep --color=auto'

# Tmux aliases
alias tl='tmux ls'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'

# Lazy navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias dev="cd ~/Documents/dev"
alias obs='cd ~/Documents/Obsidian'
alias notes='cd ~/Documents/notes'
alias dots='cd ~/.macdots'

# Run non-default vimrc
# alias vim='vim -u ~/.dev/dotfiles/vim/vimrc'
alias tmux='tmux -f ~/.macdots/tmux/tmux.conf'

# Shortcuts for git
alias gs='git status -u'
alias ga='git add'
alias gc='git commit -m '

#---
# Launch TMUX
#
tmux has-session
if [ $? != 0 ]; then
    tmux new-session -d -s main
    tmux attach -t main
fi

